import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(rootDir, "src");
const distDir = join(rootDir, "dist");
const missingValue = "MISSING_ENV_VAR";

const firebaseConfig = {
	apiKey: process.env.FIREBASE_API_KEY || missingValue,
	authDomain: process.env.FIREBASE_AUTH_DOMAIN || missingValue,
	projectId: process.env.FIREBASE_PROJECT_ID || missingValue,
	storageBucket: process.env.FIREBASE_STORAGE_BUCKET || missingValue,
	messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || missingValue,
	appId: process.env.FIREBASE_APP_ID || missingValue,
};

/**
 * 정적 앱을 Vercel 배포용 `dist` 폴더로 복사하고 Firebase 설정 파일을 생성합니다.
 *
 * Firebase 설정값은 `FIREBASE_*` 환경변수에서 읽습니다. 저장소에는 값을 남기지 않고,
 * 빌드된 `dist/config/firebase-config.js` 파일에만 기록합니다. 환경변수가 비어 있으면
 * 참고 프로젝트와 동일하게 `MISSING_ENV_VAR` 문자열을 기록해 배포 설정 누락을 눈에 띄게 합니다.
 *
 * @returns {Promise<void>} 빌드 완료를 나타내는 Promise입니다.
 */
export async function build() {
	await rm(distDir, { recursive: true, force: true });
	await mkdir(distDir, { recursive: true });
	await cp(srcDir, distDir, { recursive: true });

	const configDir = join(distDir, "config");
	await mkdir(configDir, { recursive: true });
	await writeFile(
		join(configDir, "firebase-config.js"),
		`// Generated by scripts/build.js
export const firebaseConfig = ${JSON.stringify(firebaseConfig, null, "\t")};

export default firebaseConfig;
`,
		"utf8"
	);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	build()
		.then(() => {
			console.log("dist 빌드 완료");
		})
		.catch((error) => {
			console.error(error.message);
			process.exitCode = 1;
		});
}
